/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as protectedRouteRouteImport } from './routes/(protected)/route'
import { Route as authloginIndexRouteImport } from './routes/(auth)/(login)/index'
import { Route as authRegisterIndexRouteImport } from './routes/(auth)/register/index'
import { Route as protectedDashboardIndexRouteImport } from './routes/(protected)/dashboard/index'
import { Route as protectedanalyticsPlansIndexRouteImport } from './routes/(protected)/(analytics)/plans/index'
import { Route as protectedanalyticsQuotaIndexRouteImport } from './routes/(protected)/(analytics)/quota/index'
import { Route as protectedanalyticsSettingsIndexRouteImport } from './routes/(protected)/(analytics)/settings/index'
import { Route as protectedanalyticsSystemIndexRouteImport } from './routes/(protected)/(analytics)/system/index'
import { Route as protectedanalyticsUsageIndexRouteImport } from './routes/(protected)/(analytics)/usage/index'
import { Route as protectedconnectionKeysIndexRouteImport } from './routes/(protected)/(connection)/keys/index'
import { Route as protectedconnectionMediaIndexRouteImport } from './routes/(protected)/(connection)/media/index'
import { Route as protectedconnectionProvidersIndexRouteImport } from './routes/(protected)/(connection)/providers/index'
import { Route as protectedconnectionProxyPoolsIndexRouteImport } from './routes/(protected)/(connection)/proxy-pools/index'
import { Route as protecteddeveloperCliToolsIndexRouteImport } from './routes/(protected)/(developer)/cli-tools/index'
import { Route as protecteddeveloperConsoleIndexRouteImport } from './routes/(protected)/(developer)/console/index'
import { Route as protectedsafetyGuardrailsIndexRouteImport } from './routes/(protected)/(safety)/guardrails/index'
import { Route as protectedsafetyProviderHealthIndexRouteImport } from './routes/(protected)/(safety)/provider-health/index'
import { Route as protectedtrafficChainsIndexRouteImport } from './routes/(protected)/(traffic)/chains/index'
import { Route as protectedtrafficEndpointsIndexRouteImport } from './routes/(protected)/(traffic)/endpoints/index'
import { Route as protectedtrafficSkillsIndexRouteImport } from './routes/(protected)/(traffic)/skills/index'

const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const authloginIndexRoute = authloginIndexRouteImport.update({
  id: '/(auth)/(login)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterIndexRoute = authRegisterIndexRouteImport.update({
  id: '/(auth)/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedDashboardIndexRoute = protectedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedanalyticsPlansIndexRoute =
  protectedanalyticsPlansIndexRouteImport.update({
    id: '/(analytics)/plans/',
    path: '/plans/',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedanalyticsQuotaIndexRoute =
  protectedanalyticsQuotaIndexRouteImport.update({
    id: '/(analytics)/quota/',
    path: '/quota/',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedanalyticsSettingsIndexRoute =
  protectedanalyticsSettingsIndexRouteImport.update({
    id: '/(analytics)/settings/',
    path: '/settings/',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedanalyticsSystemIndexRoute =
  protectedanalyticsSystemIndexRouteImport.update({
    id: '/(analytics)/system/',
    path: '/system/',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedanalyticsUsageIndexRoute =
  protectedanalyticsUsageIndexRouteImport.update({
    id: '/(analytics)/usage/',
    path: '/usage/',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedconnectionKeysIndexRoute =
  protectedconnectionKeysIndexRouteImport.update({
    id: '/(connection)/keys/',
    path: '/keys/',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedconnectionMediaIndexRoute =
  protectedconnectionMediaIndexRouteImport.update({
    id: '/(connection)/media/',
    path: '/media/',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedconnectionProvidersIndexRoute =
  protectedconnectionProvidersIndexRouteImport.update({
    id: '/(connection)/providers/',
    path: '/providers/',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedconnectionProxyPoolsIndexRoute =
  protectedconnectionProxyPoolsIndexRouteImport.update({
    id: '/(connection)/proxy-pools/',
    path: '/proxy-pools/',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protecteddeveloperCliToolsIndexRoute =
  protecteddeveloperCliToolsIndexRouteImport.update({
    id: '/(developer)/cli-tools/',
    path: '/cli-tools/',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protecteddeveloperConsoleIndexRoute =
  protecteddeveloperConsoleIndexRouteImport.update({
    id: '/(developer)/console/',
    path: '/console/',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedsafetyGuardrailsIndexRoute =
  protectedsafetyGuardrailsIndexRouteImport.update({
    id: '/(safety)/guardrails/',
    path: '/guardrails/',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedsafetyProviderHealthIndexRoute =
  protectedsafetyProviderHealthIndexRouteImport.update({
    id: '/(safety)/provider-health/',
    path: '/provider-health/',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedtrafficChainsIndexRoute =
  protectedtrafficChainsIndexRouteImport.update({
    id: '/(traffic)/chains/',
    path: '/chains/',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedtrafficEndpointsIndexRoute =
  protectedtrafficEndpointsIndexRouteImport.update({
    id: '/(traffic)/endpoints/',
    path: '/endpoints/',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedtrafficSkillsIndexRoute =
  protectedtrafficSkillsIndexRouteImport.update({
    id: '/(traffic)/skills/',
    path: '/skills/',
    getParentRoute: () => protectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof authloginIndexRoute
  '/register/': typeof authRegisterIndexRoute
  '/dashboard/': typeof protectedDashboardIndexRoute
  '/plans/': typeof protectedanalyticsPlansIndexRoute
  '/quota/': typeof protectedanalyticsQuotaIndexRoute
  '/settings/': typeof protectedanalyticsSettingsIndexRoute
  '/system/': typeof protectedanalyticsSystemIndexRoute
  '/usage/': typeof protectedanalyticsUsageIndexRoute
  '/keys/': typeof protectedconnectionKeysIndexRoute
  '/media/': typeof protectedconnectionMediaIndexRoute
  '/providers/': typeof protectedconnectionProvidersIndexRoute
  '/proxy-pools/': typeof protectedconnectionProxyPoolsIndexRoute
  '/cli-tools/': typeof protecteddeveloperCliToolsIndexRoute
  '/console/': typeof protecteddeveloperConsoleIndexRoute
  '/guardrails/': typeof protectedsafetyGuardrailsIndexRoute
  '/provider-health/': typeof protectedsafetyProviderHealthIndexRoute
  '/chains/': typeof protectedtrafficChainsIndexRoute
  '/endpoints/': typeof protectedtrafficEndpointsIndexRoute
  '/skills/': typeof protectedtrafficSkillsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof authloginIndexRoute
  '/register': typeof authRegisterIndexRoute
  '/dashboard': typeof protectedDashboardIndexRoute
  '/plans': typeof protectedanalyticsPlansIndexRoute
  '/quota': typeof protectedanalyticsQuotaIndexRoute
  '/settings': typeof protectedanalyticsSettingsIndexRoute
  '/system': typeof protectedanalyticsSystemIndexRoute
  '/usage': typeof protectedanalyticsUsageIndexRoute
  '/keys': typeof protectedconnectionKeysIndexRoute
  '/media': typeof protectedconnectionMediaIndexRoute
  '/providers': typeof protectedconnectionProvidersIndexRoute
  '/proxy-pools': typeof protectedconnectionProxyPoolsIndexRoute
  '/cli-tools': typeof protecteddeveloperCliToolsIndexRoute
  '/console': typeof protecteddeveloperConsoleIndexRoute
  '/guardrails': typeof protectedsafetyGuardrailsIndexRoute
  '/provider-health': typeof protectedsafetyProviderHealthIndexRoute
  '/chains': typeof protectedtrafficChainsIndexRoute
  '/endpoints': typeof protectedtrafficEndpointsIndexRoute
  '/skills': typeof protectedtrafficSkillsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/(auth)/(login)/': typeof authloginIndexRoute
  '/(auth)/register/': typeof authRegisterIndexRoute
  '/(protected)/dashboard/': typeof protectedDashboardIndexRoute
  '/(protected)/(analytics)/plans/': typeof protectedanalyticsPlansIndexRoute
  '/(protected)/(analytics)/quota/': typeof protectedanalyticsQuotaIndexRoute
  '/(protected)/(analytics)/settings/': typeof protectedanalyticsSettingsIndexRoute
  '/(protected)/(analytics)/system/': typeof protectedanalyticsSystemIndexRoute
  '/(protected)/(analytics)/usage/': typeof protectedanalyticsUsageIndexRoute
  '/(protected)/(connection)/keys/': typeof protectedconnectionKeysIndexRoute
  '/(protected)/(connection)/media/': typeof protectedconnectionMediaIndexRoute
  '/(protected)/(connection)/providers/': typeof protectedconnectionProvidersIndexRoute
  '/(protected)/(connection)/proxy-pools/': typeof protectedconnectionProxyPoolsIndexRoute
  '/(protected)/(developer)/cli-tools/': typeof protecteddeveloperCliToolsIndexRoute
  '/(protected)/(developer)/console/': typeof protecteddeveloperConsoleIndexRoute
  '/(protected)/(safety)/guardrails/': typeof protectedsafetyGuardrailsIndexRoute
  '/(protected)/(safety)/provider-health/': typeof protectedsafetyProviderHealthIndexRoute
  '/(protected)/(traffic)/chains/': typeof protectedtrafficChainsIndexRoute
  '/(protected)/(traffic)/endpoints/': typeof protectedtrafficEndpointsIndexRoute
  '/(protected)/(traffic)/skills/': typeof protectedtrafficSkillsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register/'
    | '/dashboard/'
    | '/plans/'
    | '/quota/'
    | '/settings/'
    | '/system/'
    | '/usage/'
    | '/keys/'
    | '/media/'
    | '/providers/'
    | '/proxy-pools/'
    | '/cli-tools/'
    | '/console/'
    | '/guardrails/'
    | '/provider-health/'
    | '/chains/'
    | '/endpoints/'
    | '/skills/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/dashboard'
    | '/plans'
    | '/quota'
    | '/settings'
    | '/system'
    | '/usage'
    | '/keys'
    | '/media'
    | '/providers'
    | '/proxy-pools'
    | '/cli-tools'
    | '/console'
    | '/guardrails'
    | '/provider-health'
    | '/chains'
    | '/endpoints'
    | '/skills'
  id:
    | '__root__'
    | '/(protected)'
    | '/(auth)/(login)/'
    | '/(auth)/register/'
    | '/(protected)/dashboard/'
    | '/(protected)/(analytics)/plans/'
    | '/(protected)/(analytics)/quota/'
    | '/(protected)/(analytics)/settings/'
    | '/(protected)/(analytics)/system/'
    | '/(protected)/(analytics)/usage/'
    | '/(protected)/(connection)/keys/'
    | '/(protected)/(connection)/media/'
    | '/(protected)/(connection)/providers/'
    | '/(protected)/(connection)/proxy-pools/'
    | '/(protected)/(developer)/cli-tools/'
    | '/(protected)/(developer)/console/'
    | '/(protected)/(safety)/guardrails/'
    | '/(protected)/(safety)/provider-health/'
    | '/(protected)/(traffic)/chains/'
    | '/(protected)/(traffic)/endpoints/'
    | '/(protected)/(traffic)/skills/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
  authloginIndexRoute: typeof authloginIndexRoute
  authRegisterIndexRoute: typeof authRegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/(login)/': {
      id: '/(auth)/(login)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authloginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register/': {
      id: '/(auth)/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof authRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/dashboard/': {
      id: '/(protected)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof protectedDashboardIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/(analytics)/plans/': {
      id: '/(protected)/(analytics)/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof protectedanalyticsPlansIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/(analytics)/quota/': {
      id: '/(protected)/(analytics)/quota/'
      path: '/quota'
      fullPath: '/quota/'
      preLoaderRoute: typeof protectedanalyticsQuotaIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/(analytics)/settings/': {
      id: '/(protected)/(analytics)/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof protectedanalyticsSettingsIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/(analytics)/system/': {
      id: '/(protected)/(analytics)/system/'
      path: '/system'
      fullPath: '/system/'
      preLoaderRoute: typeof protectedanalyticsSystemIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/(analytics)/usage/': {
      id: '/(protected)/(analytics)/usage/'
      path: '/usage'
      fullPath: '/usage/'
      preLoaderRoute: typeof protectedanalyticsUsageIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/(connection)/keys/': {
      id: '/(protected)/(connection)/keys/'
      path: '/keys'
      fullPath: '/keys/'
      preLoaderRoute: typeof protectedconnectionKeysIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/(connection)/media/': {
      id: '/(protected)/(connection)/media/'
      path: '/media'
      fullPath: '/media/'
      preLoaderRoute: typeof protectedconnectionMediaIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/(connection)/providers/': {
      id: '/(protected)/(connection)/providers/'
      path: '/providers'
      fullPath: '/providers/'
      preLoaderRoute: typeof protectedconnectionProvidersIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/(connection)/proxy-pools/': {
      id: '/(protected)/(connection)/proxy-pools/'
      path: '/proxy-pools'
      fullPath: '/proxy-pools/'
      preLoaderRoute: typeof protectedconnectionProxyPoolsIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/(developer)/cli-tools/': {
      id: '/(protected)/(developer)/cli-tools/'
      path: '/cli-tools'
      fullPath: '/cli-tools/'
      preLoaderRoute: typeof protecteddeveloperCliToolsIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/(developer)/console/': {
      id: '/(protected)/(developer)/console/'
      path: '/console'
      fullPath: '/console/'
      preLoaderRoute: typeof protecteddeveloperConsoleIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/(safety)/guardrails/': {
      id: '/(protected)/(safety)/guardrails/'
      path: '/guardrails'
      fullPath: '/guardrails/'
      preLoaderRoute: typeof protectedsafetyGuardrailsIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/(safety)/provider-health/': {
      id: '/(protected)/(safety)/provider-health/'
      path: '/provider-health'
      fullPath: '/provider-health/'
      preLoaderRoute: typeof protectedsafetyProviderHealthIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/(traffic)/chains/': {
      id: '/(protected)/(traffic)/chains/'
      path: '/chains'
      fullPath: '/chains/'
      preLoaderRoute: typeof protectedtrafficChainsIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/(traffic)/endpoints/': {
      id: '/(protected)/(traffic)/endpoints/'
      path: '/endpoints'
      fullPath: '/endpoints/'
      preLoaderRoute: typeof protectedtrafficEndpointsIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/(traffic)/skills/': {
      id: '/(protected)/(traffic)/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof protectedtrafficSkillsIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
  }
}

interface protectedRouteRouteChildren {
  protectedDashboardIndexRoute: typeof protectedDashboardIndexRoute
  protectedanalyticsPlansIndexRoute: typeof protectedanalyticsPlansIndexRoute
  protectedanalyticsQuotaIndexRoute: typeof protectedanalyticsQuotaIndexRoute
  protectedanalyticsSettingsIndexRoute: typeof protectedanalyticsSettingsIndexRoute
  protectedanalyticsSystemIndexRoute: typeof protectedanalyticsSystemIndexRoute
  protectedanalyticsUsageIndexRoute: typeof protectedanalyticsUsageIndexRoute
  protectedconnectionKeysIndexRoute: typeof protectedconnectionKeysIndexRoute
  protectedconnectionMediaIndexRoute: typeof protectedconnectionMediaIndexRoute
  protectedconnectionProvidersIndexRoute: typeof protectedconnectionProvidersIndexRoute
  protectedconnectionProxyPoolsIndexRoute: typeof protectedconnectionProxyPoolsIndexRoute
  protecteddeveloperCliToolsIndexRoute: typeof protecteddeveloperCliToolsIndexRoute
  protecteddeveloperConsoleIndexRoute: typeof protecteddeveloperConsoleIndexRoute
  protectedsafetyGuardrailsIndexRoute: typeof protectedsafetyGuardrailsIndexRoute
  protectedsafetyProviderHealthIndexRoute: typeof protectedsafetyProviderHealthIndexRoute
  protectedtrafficChainsIndexRoute: typeof protectedtrafficChainsIndexRoute
  protectedtrafficEndpointsIndexRoute: typeof protectedtrafficEndpointsIndexRoute
  protectedtrafficSkillsIndexRoute: typeof protectedtrafficSkillsIndexRoute
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedDashboardIndexRoute: protectedDashboardIndexRoute,
  protectedanalyticsPlansIndexRoute: protectedanalyticsPlansIndexRoute,
  protectedanalyticsQuotaIndexRoute: protectedanalyticsQuotaIndexRoute,
  protectedanalyticsSettingsIndexRoute: protectedanalyticsSettingsIndexRoute,
  protectedanalyticsSystemIndexRoute: protectedanalyticsSystemIndexRoute,
  protectedanalyticsUsageIndexRoute: protectedanalyticsUsageIndexRoute,
  protectedconnectionKeysIndexRoute: protectedconnectionKeysIndexRoute,
  protectedconnectionMediaIndexRoute: protectedconnectionMediaIndexRoute,
  protectedconnectionProvidersIndexRoute:
    protectedconnectionProvidersIndexRoute,
  protectedconnectionProxyPoolsIndexRoute:
    protectedconnectionProxyPoolsIndexRoute,
  protecteddeveloperCliToolsIndexRoute: protecteddeveloperCliToolsIndexRoute,
  protecteddeveloperConsoleIndexRoute: protecteddeveloperConsoleIndexRoute,
  protectedsafetyGuardrailsIndexRoute: protectedsafetyGuardrailsIndexRoute,
  protectedsafetyProviderHealthIndexRoute:
    protectedsafetyProviderHealthIndexRoute,
  protectedtrafficChainsIndexRoute: protectedtrafficChainsIndexRoute,
  protectedtrafficEndpointsIndexRoute: protectedtrafficEndpointsIndexRoute,
  protectedtrafficSkillsIndexRoute: protectedtrafficSkillsIndexRoute,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  protectedRouteRoute: protectedRouteRouteWithChildren,
  authloginIndexRoute: authloginIndexRoute,
  authRegisterIndexRoute: authRegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
