// @ts-nocheck
import * as __fd_glob_45 from "../content/docs/id-ID/concepts/skills.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/id-ID/concepts/routing.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/id-ID/concepts/providers.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/id-ID/concepts/plans-budgets.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/id-ID/concepts/guardrails.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/id-ID/concepts/api-keys.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/id-ID/gateway/streaming.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/id-ID/gateway/responses.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/id-ID/gateway/model-addressing.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/id-ID/gateway/messages.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/id-ID/gateway/index.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/id-ID/gateway/errors.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/id-ID/gateway/chat-completions.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/id-ID/getting-started/installation.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/id-ID/getting-started/dashboard.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/id-ID/api-reference/dashboard-api.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/id-ID/index.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/id-ID/configuration.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/getting-started/installation.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/getting-started/dashboard.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/api-reference/dashboard-api.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/gateway/streaming.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/gateway/responses.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/gateway/model-addressing.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/gateway/messages.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/gateway/index.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/gateway/errors.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/gateway/chat-completions.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/concepts/skills.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/concepts/routing.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/concepts/providers.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/concepts/plans-budgets.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/concepts/guardrails.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/concepts/api-keys.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/index.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/configuration.mdx?collection=docs"
import { default as __fd_glob_9 } from "../content/docs/id-ID/concepts/meta.json?collection=docs"
import { default as __fd_glob_8 } from "../content/docs/id-ID/getting-started/meta.json?collection=docs"
import { default as __fd_glob_7 } from "../content/docs/id-ID/gateway/meta.json?collection=docs"
import { default as __fd_glob_6 } from "../content/docs/id-ID/api-reference/meta.json?collection=docs"
import { default as __fd_glob_5 } from "../content/docs/concepts/meta.json?collection=docs"
import { default as __fd_glob_4 } from "../content/docs/id-ID/meta.json?collection=docs"
import { default as __fd_glob_3 } from "../content/docs/getting-started/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/gateway/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/api-reference/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_0, "api-reference/meta.json": __fd_glob_1, "gateway/meta.json": __fd_glob_2, "getting-started/meta.json": __fd_glob_3, "id-ID/meta.json": __fd_glob_4, "concepts/meta.json": __fd_glob_5, "id-ID/api-reference/meta.json": __fd_glob_6, "id-ID/gateway/meta.json": __fd_glob_7, "id-ID/getting-started/meta.json": __fd_glob_8, "id-ID/concepts/meta.json": __fd_glob_9, }, {"configuration.mdx": __fd_glob_10, "index.mdx": __fd_glob_11, "concepts/api-keys.mdx": __fd_glob_12, "concepts/guardrails.mdx": __fd_glob_13, "concepts/plans-budgets.mdx": __fd_glob_14, "concepts/providers.mdx": __fd_glob_15, "concepts/routing.mdx": __fd_glob_16, "concepts/skills.mdx": __fd_glob_17, "gateway/chat-completions.mdx": __fd_glob_18, "gateway/errors.mdx": __fd_glob_19, "gateway/index.mdx": __fd_glob_20, "gateway/messages.mdx": __fd_glob_21, "gateway/model-addressing.mdx": __fd_glob_22, "gateway/responses.mdx": __fd_glob_23, "gateway/streaming.mdx": __fd_glob_24, "api-reference/dashboard-api.mdx": __fd_glob_25, "getting-started/dashboard.mdx": __fd_glob_26, "getting-started/installation.mdx": __fd_glob_27, "id-ID/configuration.mdx": __fd_glob_28, "id-ID/index.mdx": __fd_glob_29, "id-ID/api-reference/dashboard-api.mdx": __fd_glob_30, "id-ID/getting-started/dashboard.mdx": __fd_glob_31, "id-ID/getting-started/installation.mdx": __fd_glob_32, "id-ID/gateway/chat-completions.mdx": __fd_glob_33, "id-ID/gateway/errors.mdx": __fd_glob_34, "id-ID/gateway/index.mdx": __fd_glob_35, "id-ID/gateway/messages.mdx": __fd_glob_36, "id-ID/gateway/model-addressing.mdx": __fd_glob_37, "id-ID/gateway/responses.mdx": __fd_glob_38, "id-ID/gateway/streaming.mdx": __fd_glob_39, "id-ID/concepts/api-keys.mdx": __fd_glob_40, "id-ID/concepts/guardrails.mdx": __fd_glob_41, "id-ID/concepts/plans-budgets.mdx": __fd_glob_42, "id-ID/concepts/providers.mdx": __fd_glob_43, "id-ID/concepts/routing.mdx": __fd_glob_44, "id-ID/concepts/skills.mdx": __fd_glob_45, });