# syntax=docker/dockerfile:1

# Builds the docs site (apps/docs, Next.js) into a standalone Node image.
# Published separately from the server image by the "release-docs" job in
# .github/workflows/release.yml.

# ====================================================================================
# Stage 1: build (pnpm install + next build -> .next/standalone)
# ====================================================================================
FROM node:24-alpine AS build

WORKDIR /build

# The workspace manifest and lockfile must be present before install so pnpm
# resolves the frozen workspace graph.
COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./
COPY apps/docs/package.json apps/docs/package.json

RUN corepack enable && pnpm install --frozen-lockfile --filter @tera/docs

# .source is generated by fumadocs-mdx during the build; it is not in the
# context (see .dockerignore).
COPY apps/docs apps/docs

RUN pnpm --filter @tera/docs exec next build

# ====================================================================================
# Stage 2: runtime (standalone server, no node_modules)
# ====================================================================================
FROM node:24-alpine

ENV NODE_ENV=production \
    HOSTNAME=0.0.0.0 \
    PORT=3000

RUN addgroup -S docs && adduser -S docs -G docs

# In a workspace, the standalone tree mirrors the monorepo layout, so the
# entrypoint sits at apps/docs/server.js and Next resolves .next/static and
# public relative to it.
WORKDIR /app

COPY --from=build /build/apps/docs/.next/standalone ./
COPY --from=build /build/apps/docs/.next/static ./apps/docs/.next/static
COPY --from=build /build/apps/docs/public ./apps/docs/public

USER docs

EXPOSE 3000

CMD ["node", "apps/docs/server.js"]
